DROP TABLE IF EXISTS car;
CREATE TABLE car (
    idCar INT NOT NULL AUTO_INCREMENT,
    model VARCHAR(20) NOT NULL,
    color VARCHAR(20) NOT NULL,
    yearOfIssue INT NOT NULL,
    carNumber VARCHAR(7) NOT NULL,
    PRIMARY KEY (idCar)
);